# Generated by Django 3.1.2 on 2020-10-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='headline',
            field=models.CharField(default='Sample Title', max_length=150),
            preserve_default=False,
        ),
    ]
